### ISSUE TITLE
warning `disp_driver_init` return with value

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl_esp32_drivers#106]
I'm getting this warning:

```console
lv_port_esp32/components/lvgl_esp32_drivers/lvgl_tft/disp_driver.c:70:12: warning: 'return' with a value, in function returning void
     return NULL;
            ^~~~
```

Introduced here, could you take a look @tore-espressif ?
```c
#if (defined(CONFIG_LV_DISP_BACKLIGHT_SWITCH) || defined(CONFIG_LV_DISP_BACKLIGHT_PWM))
    const disp_backlight_config_t bckl_config = {
        .gpio_num = CONFIG_LV_DISP_PIN_BCKL,
#if defined CONFIG_LV_DISP_BACKLIGHT_PWM
        .pwm_control = true,
#else
        .pwm_control = false,
#endif
#if defined CONFIG_LV_BACKLIGHT_ACTIVE_LVL
        .output_invert = false, // Backlight on high
#else
        .output_invert = true, // Backlight on low
#endif
        .timer_idx = 0,
        .channel_idx = 0 // @todo this prevents us from having two PWM controlled displays
    };
    disp_backlight_h bckl_handle = disp_backlight_new(&bckl_config);
    disp_backlight_set(bckl_handle, 100);
    return bckl_handle;
#else
    return NULL;
#endif
}
```

**Comment by tore-espressif** [comment]
This was all introduced in the backlight PR https://github.com/lvgl/lvgl_esp32_drivers/pull/95

The idea is to separate backlight controller from the display driver. The `void *disp_driver_init(void)` function returns a pointer to backlight controller handle (if it was configured in Kconfig). It is not the best solution, but it fits the current architecture.

You changed it back in your PR https://github.com/lvgl/lvgl_esp32_drivers/pull/92/files#diff-8017a67c23d46b1d9c8c9f407a88b42e0f2341a4acd769c1e34943dfdb075b8eL10

So the question is, whether you changed it intentionally, or just by mistake (during rebase)?

**Comment by tore-espressif** [comment]
Just guessing: did you rebase on `master` ? You should have rebased on `develop` when you want to merge to `develop`.

If you do it the other way around you might accidentally revert all commit thats are in `develop` but not in `master`

**Comment by C47D** [comment]
I see, I rebased on my development branch. So, the easiest fix is changing the return type of the function, isn't?

I was also thinking of removing the backlight control from the driver code, what do you think?

**Comment by C47D** [comment]
Yep, it was my fault, just updated my project and the warning no longer pops up 😅
