### ISSUE TITLE
ft6x36 invert before swap can lead to negetive numbers

### ISSUE THREAD

**Issue by morganrallen** [lvgl/lvgl_esp32_drivers#110]
The `ft6x36_read` function call has three `CONFIG_` checks to perform `INVERT_X`, `INVERT_Y` and `SWAPXY`.
It appears because the swap happens after the inversions it can result in negative numbers. To get it working for myself I just changed the order, but I suspect this might vary from one setup to another.

**Comment by C47D** [comment]
Hi @morganrallen,
Does the fix in #118 solves the issue? I've merged the suggested fix in master.

**Comment by morganrallen** [comment]
Yup, looks good

**Comment by C47D** [comment]
Can we close the issue?
