### ISSUE TITLE
ft6x36 touch IC returns false after a successful read.

### ISSUE THREAD

**Issue by Ali-Abdelwdod** [lvgl/lvgl_esp32_drivers#141]
the function ft6x36_read returns false even when the function detects a single touch successfully!

**Comment by embeddedt** [comment]
This is the intended behavior ([related documentation](https://docs.lvgl.io/7.11/porting/indev.html#types-of-input-devices)). The return value is intended to indicate whether there are more queued touch events to process, not whether there has been a touch. Returning `true` if there was just one touch would cause LVGL to block indefinitely in [this loop](https://github.com/lvgl/lvgl/blob/ec4435426ef62b8b963acc81f0e885680a65e352/src/lv_core/lv_indev.c#L90-L123).
