### ISSUE TITLE
Using a third SPI peripheral with LVGLs Display and Touch drivers

### ISSUE THREAD

**Issue by BFFonseca** [lvgl/lvgl_esp32_drivers#16]
**Describe the issue**
I'm using an ESP32 with a ILI9341 driver display and a XPT2046 touch driver. They're both running on HSPI.

I'm trying to incorporate another SPI peripheral in the same bus (HSPI).

In the ESP32 documentation it says it is possible to have 3 peripherals per SPI bus.

When I try to use the same SPI bus for all of these, I get the error:
```
E (8973) spi: SPI2 already claimed by spi master.
E (8983) spi_master: spi_bus_initialize(232): host already in use
```

I am initializing the 3rd SPI peripheral like this:
```
  spi_bus_config_t bus = {
       .miso_io_num = 19,
       .mosi_io_num = 13,
       .sclk_io_num = 14,
       .quadwp_io_num = -1,
       .quadhd_io_num = -1,
       .max_transfer_sz = 0};

   ret = spi_bus_initialize(HSPI_HOST, &bus, 1);
   assert(ret == ESP_OK);

   spi_device_interface_config_t dev = {
       .clock_speed_hz = 9000000,
       .mode = 0,
       .spics_io_num = 5,
       .queue_size = 1,
       .flags = 0,
       .pre_cb = NULL};
   ret = spi_bus_add_device(HSPI_HOST, &dev, &__spi);
```
As for LVGL, I'm using the same SPI pins and 
```
DISP_SPI_CS 12
TOUCH_SPI_CS 32
```
I am initializing LVGL first and only (works normally, both the display and the touch panel) and then the other peripheral, on a separate task.

**ESP32 Chip version**
ESP32-WROOM-32

**ESP-IDF version**
ESP-IDF 4.1 

**Development kit used**
ESP 32 DEVKIT V1

**Development machine OS**
Ubuntu 14.04.5 LTS

**Comment by Silvesterrr** [comment]
> I'm currently working on adding a SD card connected via SPI (same spi of the display controller) for a personal project, will update if I'm able to make it work.

I was able to make it work for anyone concern (esp32-s3, ILI9486, XPT2046)
Here is my lvgl driver for it.
[sd_driver.txt](https://github.com/lvgl/lvgl_esp32_drivers/files/9632486/sd_driver.txt)
