### ISSUE TITLE
ST7789: Make display offset runtime configurable 

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl_esp32_drivers#163]
St7789 based displays has several offset configurations, trying to handle all of the options in the flush callback will become harder. A runtime configuration will ease the handling of said offsets.

**Comment by C47D** [comment]
Closed with #164

**Comment by tore-espressif** [comment]
Offsets are now handled by LVGL see https://github.com/lvgl/lvgl/pull/2583 !
