### ISSUE TITLE
ESP32-S2 Projects cannot use pin numbers higher than 39 when configuring through menuconfig

### ISSUE THREAD

**Issue by jockm** [lvgl/lvgl_esp32_drivers#28]
The ESP32-S2 has more available GPIOs than the ESP32, but menuconfig only allows assigning pins 0-39.

It remains clear that no testing or consideration of the -S2 chip has been given.

Again I must stress the need to publicly document that the -S2 chip is currently unsupported

**Comment by C47D** [comment]
I've pushed a couple of commits that should allow you to select pins from 0 to 43 in the [fix/esp32-s2-gpios](https://github.com/lvgl/lvgl_esp32_drivers/tree/fix/esp32-s2-gpios)

![imagen](https://user-images.githubusercontent.com/11037705/106853626-a2044280-667f-11eb-9f9f-dba68f3a5c21.png)

Can you test it? You can do it by fetching the `lvgl_esp32_drivers` repo and then `git checkout --track origin/fix/esp32-s2-gpios'

**Comment by jockm** [comment]
Works perfectly tested as both ESP32 and ESP32-S2 to see the pin ranges were appropriate for each, and looked at each pin assignments.  All good.  Ship It! ;)

**Comment by C47D** [comment]
> All good. Ship It! ;)

Told you this issue was the easiest one.
