### ISSUE TITLE
ST7789 color inversion

### ISSUE THREAD

**Issue by tore-espressif** [lvgl/lvgl_esp32_drivers#38]
For reasons unknown (missing git history) ST7789 driver inverts colors by default:

https://github.com/lvgl/lvgl_esp32_drivers/blob/master/lvgl_tft/st7789.c#L68

This has to be made configurable. 

This is more-or-less a feature request, as most of the LCD displays support color inversion.

**Comment by C47D** [comment]
The git history was lost when we moved the `lvgl_esp32_drivers` content from the `lv_port_esp32` repo into it's own repo (this one). I didn't knew on how to do it properly.
