### ISSUE TITLE
Remove LV_DISPLAY_HEIGHT and LV_DISPLAY_WIDTH from display Kconfig

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl_esp32_drivers#5]
That option is available in LVGL Kconfig.

**Comment by VedantParanjape** [comment]
Hi, I encountered issue due to this. It is misleading to have two different parameters controlling the size of a display.

When will this be fixed ?

**Comment by C47D** [comment]
I will be able to work on this over the weekend. First weekend of 2021!

**Comment by VedantParanjape** [comment]
Hi, sounds good. If you need any help let me know. I mean assign this issue to me.

**Comment by C47D** [comment]
Hi, I will look into this today, I built the project yesterday and had no issues. I will let you know later today if I assign this to you.

**Comment by VedantParanjape** [comment]
> Hi, I will look into this today, I built the project yesterday and had no issues. I will let you know later today if I assign this to you.

Cool, it builds okay. but the docs completely missed this.

So, my code worked on 1st December and then I was trying to make it run on 31st December and it didn't work and I spent a good one day scratching my head, as to why it won't work.

**Comment by C47D** [comment]
Can you try switching the lvgl_esp32_drivers submodule on lv_port_esp32 to follow [this ](https://github.com/lvgl/lvgl_esp32_drivers/tree/remove_redundand_config) branch?

**Comment by VedantParanjape** [comment]
> Can you try switching the lvgl_esp32_drivers submodule on lv_port_esp32 to follow this branch?

I have been able to get it work for now, I'll wait till you merge into master

**Comment by C47D** [comment]
Did you had any other issues? I haven't been able to test it with hardware, I only compiled the project.

**Comment by VedantParanjape** [comment]
> Did you had any other issues? I haven't been able to test it with hardware, I only compiled the project.

no other issues, it worked with ssd1306 oled 128x64 module.

**Comment by C47D** [comment]
Nice, I will merge the branch.

**Comment by VedantParanjape** [comment]
Hi, @C47D. but in many places the code was using the macros that were removed.

**Comment by C47D** [comment]
Lvgl configuration have both `LV_HOR_RES_MAX` and `LV_VER_RES_MAX`,  `LV_DISPLAY_ORIENTATION` was kept on the configuration options.

Are you getting compilation errors?

**Comment by VedantParanjape** [comment]
@C47D https://github.com/lvgl/lvgl_esp32_drivers/blob/1cda575dac44c25be62df821abfff0756dcb7dd3/lvgl_helpers.h#L41

You are still using `CONFIG_LV_DISPLAY_WIDTH` and `CONFIG_LV_DISPLAY_HEIGHT` in many places in code, but you removed it from kconfig, so I guess it will throw a error, right ?

**Comment by C47D** [comment]
You're right, I don't know why the compilation didn't failed, maybe the undefined symbols are set to 0.

**Comment by VedantParanjape** [comment]
> You're right, I don't know why the compilation didn't failed, maybe the undefined symbols are set to 0.

It's going to be a nightmare to remove these. Just a suggestion, group all the macros from kconfig in one single header, easier to manage.

**Comment by C47D** [comment]
I've already removed all references to those symbols, I forgot the name of the branch I've used. 

There's a lot of cleanup on the code base, the ultimate goal is to add all of the drivers into lv_drivers, for that we need to make them mcu/framework independent.

**Comment by VedantParanjape** [comment]
> There's a lot of cleanup on the code base, the ultimate goal is to add all of the drivers into lv_drivers, for that we need to make them mcu/framework independent. 

You could look at HAL used by u8g2

**Comment by VedantParanjape** [comment]
Don't know if this is relevant in this issue, let me know if you want me to move to new issue.

here's my code: https://pastebin.com/6EQgP0Dh

when I boot my board, it shows a static text "Text" on the upper left corner of the screen as follows

![IMG_20210112_001739](https://user-images.githubusercontent.com/22630228/104225340-4540ae00-546c-11eb-8407-1ed9d180b05d.jpg)

**Comment by C47D** [comment]
@VedantParanjape let's move it into a new issue. Have you configured LV_SPRINTF_FLOAT_DISABLE? You're using a float format on your label.

**Comment by VedantParanjape** [comment]
> @VedantParanjape let's move it into a new issue. Have you configured LV_SPRINTF_FLOAT_DISABLE? You're using a float format on your label.

Cool. I'll create a new issue in the main repository 👍🏻

> Also your for loop (right before the infinite loop) have no brackets. I will try to replicate your issue later today, got my stuff at home.

Ah, that was a typo, I'll fix it.

**Comment by C47D** [comment]
Ok, let's follow over there.
