### ISSUE TITLE
nscreen32 support 

### ISSUE THREAD

**Issue by linkineo** [lvgl/lvgl_esp32_drivers#62]
I could make my app work on an esp32-wrover kit without any problems thanks to your great lib.
I then ordered the nscreen32, the "1st lvgl certified board in the world", but there seems to be no predefined configuration in menuconfig for it. Even if it's ST7796 TFT controller is available in the options, the Goodix touch controller does not seem supported yet. 
Also, the [code](https://github.com/yeacreate-opensources/Nscreen_32) provided for the board seems to be arduino code only, but not really a component I can use out of the box with the esp-idf.
Are there any plans from lvgl to support the nscreen32 ?

**Comment by kisvegabor** [comment]
I've notified the author of the NScreen32.

**Comment by simonchen007** [comment]
@linkineo  , the driver of Nscreen32 is here:
https://github.com/yeacreate-opensources/Nscreen_32/blob/master/lvgl_demo/src/gt911.cpp

we will try to port it to https://github.com/lvgl/lvgl_esp32_drivers

**Comment by linkineo** [comment]
@simonchen007 thanks for your reply. 
This is the driver for the Goodix touch controller only, right ? Also, it is made for Wiring/Arduino, so it won't work as an esp32 component out of the box. 
What would be nice is to have something equivalent in the esp-idf menuconfig of the lvgl driver that enables to select the Nscreen32, with the consequence of correctly setting all pins and settings for lvgl :-) This would include the ST7796 and the Goodix controller. Would be awesome.

**Comment by simonchen007** [comment]
@linkineo 
Thing is that, we have developed it as component of ESP-IDF when we making the ST7796 driver before. but very low performed we got, in this case we stopped develop the ESP-IDF component. And move all codes to Arduino (esp32-arduino can have about 2-3 times performed). Now , we have to check out old codes(the ESP-IDF component version).

**Comment by linkineo** [comment]
@simonchen007 ok I understand. I was just asking because esp-idf compatibility is promoted on this [page](https://blog.lvgl.io/2021-03-23/yeacreate-nscreen32-review). 
Anyway, what could be helpful as a starter would just be to post a sample menuconfig for a given version of the lvgl_esp32_drivers that could allow seeing the performance for ourselves and maybe improve together. This would just entail telling us which pins and which lvgl settings we need to adapt to get the basic demo working. Even if touch is not supported, that could wait, and maybe I could help to port this part. 
But basically, it would help just knowing how to configure the ST7796 with the current drivers to display the lvgl demo. The rest could wait :-)

**Comment by kisvegabor** [comment]
> @simonchen007 ok I understand. I was just asking because esp-idf compatibility is promoted on this page.

Oh, my bad, sorry. Just fixed it.
