### ISSUE TITLE
No longer compiles on ESP-IDF v4.3 or earlier

### ISSUE THREAD

**Issue by Jascha-N** [lvgl/lvgl_esp32_drivers#94]
#74 broke compilation on v4.3 and earlier. The problematic line: https://github.com/lvgl/lvgl_esp32_drivers/blob/5d4334a5b9eaca15b7f9deaa0b734b23ba9ca811/lvgl_tft/esp_lcd_backlight.c#L28

`.flags` seems to only be available on the ESP-IDF master branch.

**Comment by tore-espressif** [comment]
Thanks, will be fixed here https://github.com/lvgl/lvgl_esp32_drivers/pull/95
